### ISSUE TITLE
String vs Boolean

### ISSUE THREAD

**Issue by TerminalFi** [twelvesec/roben#2]
Why is a string being used here instead of passing a boolean value?

https://github.com/twelvesec/roben/blob/ebc8840fd2e0b919c74dc2908ab2d0f34ece1519/roben.py#L62

**Comment by nickvourd** [comment]
It is python, no matters Boolean or strings

**Comment by TerminalFi** [comment]
I mean, they are different for a reason. Sure you can still test against a string but why not just test such as the following. I just don't see why you use strings like that.

```python
if flag:
    pass

if not flag:
    pass
```

**Comment by nickvourd** [comment]
We will fix it ASAP, however this piece of code doesn't troubleshooting the functionality of the main program!
